---
title: "wanikani goods"
---

[Wanikani](https://www.wanikani.com/) is an integral part of my strategy for learning Japanese. It is an online Structured Reptition System program for learning more than 2000 kanji and lots of vocabulary. The community that has developed around Wanikani is also a great inspiration for code projects building on the open data model that wanikani follows. Here are some of mine.

- [wanikani-writing](https://gwmatthews.github.io/wanikani-writing/): printable kanji writing practice sheets organized by Wanikani levels. The [repository is here](https://github.com/gwmatthews/wanikani-writing).

- [wanikani-cards](https://github.com/gwmatthews/wanikani-cards): these are some cards with kanji in sets arranged by Wanikani levels. More cheat sheets than flashcards. There's also some with the first 20 levels of radicals.
- [flashcards](https://gwmatthews.github.io/wanikani-flashcards/): well I wasn't going to make flashcards of all of the gazillions of kanji and vocabulary at Wanikani, but then I saw it as a coding challenge since I could easily download lots of csv files with various lists of kanji and Japanese words along with their readings and meanings. You can find premade copies of sheets with 15 cards each of the various kanji and vocab words (vocab only up to level 20) at the repository linked above. And if you have the right software (LaTeX, sed, awk, xelatex, etc.) on your linux computer you can make your own custom sets with the code. [Here is the repository](https://github.com/gwmatthews/wanikani-flashcards) where you can get the code to play with.